onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/cgra/S_AXI_ACLK_I
add wave -noupdate /tb/cgra/CGRA_CLK
add wave -noupdate /tb/cgra/RST_N_I
add wave -noupdate /tb/cgra/EN_I
add wave -noupdate /tb/S_AXI_AWADDR
add wave -noupdate /tb/S_AXI_AWLEN
add wave -noupdate /tb/S_AXI_AWVALID
add wave -noupdate /tb/S_AXI_AWREADY
add wave -noupdate /tb/S_AXI_WREADY
add wave -noupdate /tb/S_AXI_WVALID
add wave -noupdate /tb/S_AXI_WLAST
add wave -noupdate /tb/S_AXI_WDATA
add wave -noupdate /tb/cgra/axi_interface/S_AXI_WREADY
add wave -noupdate /tb/cgra/axi_interface/S_AXI_WVALID
add wave -noupdate /tb/cgra/axi_interface/S_AXI_WLAST
add wave -noupdate /tb/cgra/axi_interface/S_AXI_AWVALID
add wave -noupdate /tb/cgra/axi_interface/S_AXI_AWREADY
add wave -noupdate /tb/cgra/axi_interface/S_AXI_AWADDR
add wave -noupdate /tb/cgra/axi_interface/filtered
add wave -noupdate /tb/cgra/axi_interface/data_0
add wave -noupdate /tb/cgra/axi_interface/incoming_len
add wave -noupdate /tb/cgra/axi_interface/incoming_type
add wave -noupdate /tb/cgra/axi_interface/incoming_addr
add wave -noupdate /tb/cgra/axi_interface/incoming_id
add wave -noupdate /tb/cgra/axi_interface/incoming_op
add wave -noupdate /tb/cgra/axi_interface/burst_len
add wave -noupdate /tb/cgra/axi_interface/burst_type
add wave -noupdate /tb/cgra/axi_interface/burst_addr
add wave -noupdate /tb/cgra/axi_interface/burst_id
add wave -noupdate /tb/cgra/axi_interface/burst_op
add wave -noupdate /tb/cgra/axi_interface/burst_hold
add wave -noupdate /tb/cgra/axi_interface/transfer_cntr
add wave -noupdate /tb/cgra/axi_interface/valid_context
add wave -noupdate /tb/cgra/axi_interface/burst_underway
add wave -noupdate /tb/cgra/axi_interface/enable_write_ctrl
add wave -noupdate /tb/cgra/axi_interface/ctrl_was_triggered
add wave -noupdate /tb/cgra/axi_interface/allowed_to_proceed
add wave -noupdate /tb/cgra/axi_interface/ENABLE_WRITE_CTRL_O
add wave -noupdate /tb/cgra/axi_interface/VALID_CONTEXT_O
add wave -noupdate /tb/cgra/axi_interface/CONTEXT_ADDR_O
add wave -noupdate /tb/cgra/axi_interface/AFFECTED_MODULE_O
add wave -noupdate /tb/cgra/axi_interface/PARAMETER_BUFFER_DESTINATION_O
add wave -noupdate /tb/cgra/axi_interface/OPERATION_O
add wave -noupdate /tb/cgra/axi_interface/DATA_0_O
add wave -noupdate /tb/cgra/ctrl_contextEn_pe0
add wave -noupdate /tb/cgra/ctrl_contextEn_pe1
add wave -noupdate /tb/cgra/ctrl_contextEn_pe2
add wave -noupdate /tb/cgra/ctrl_contextEn_pe3
add wave -noupdate /tb/cgra/ccu_context_wr_en
add wave -noupdate /tb/cgra/cbox_context_wr_en
add wave -noupdate /tb/cgra/idc_wr_en
add wave -noupdate /tb/cgra/parameter_buffer_wr_en
add wave -noupdate /tb/cgra/syncUnit_wr_en
add wave -noupdate /tb/cgra/glog_context_wr_en
add wave -noupdate /tb/cgra/sensor_context_wr_en
add wave -noupdate /tb/cgra/actor_context_wr_en
add wave -noupdate /tb/cgra/context_wr_en
add wave -noupdate /tb/cgra/w_incoming_context_data_0
add wave -noupdate /tb/cgra/w_incoming_context_data_1
add wave -noupdate /tb/cgra/ctrl_parameterEn_pe0
add wave -noupdate /tb/cgra/ctrl_parameterEn_pe1
add wave -noupdate /tb/cgra/ctrl_parameterEn_pe2
add wave -noupdate /tb/cgra/ctrl_parameterEn_pe3
add wave -noupdate /tb/cgra/parameter_context_preped
add wave -noupdate /tb/cgra/parameter_buffer_empty
add wave -noupdate /tb/cgra/parameter_buffer_full
add wave -noupdate /tb/cgra/parameter_data
add wave -noupdate /tb/cgra/parameter_target_pe
add wave -noupdate /tb/cgra/rf_wr_addr
add wave -noupdate /tb/cgra/state
add wave -noupdate /tb/cgra/next_state
add wave -noupdate /tb/cgra/enable_controlunit_sync
add wave -noupdate /tb/cgra/ccu_load_en_sync
add wave -noupdate /tb/cgra/enable_datapath_modules_sync
add wave -noupdate /tb/cgra/parameter_update_allowed_sync
TreeUpdate [SetDefaultTree]
quietly wave cursor active 1
configure wave -namecolwidth 300
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {200ns} {400ns}
